##USERS

###GETALL
GET http://localhost:8080/api/users
Accept: application/json

###GETBYID
GET http://localhost:8080/api/users/id/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1MjAwNjQ2MCwiZXhwIjoxNzUyMDA3MzYwfQ.0cq8HSoK6cbahQNdVfvy1HJCWJ_ptI3EZykwx-X9ukM


###POST
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "dolly",
  "surname": "HERRERA GARCIA DA ROSA",
  "identityNumber": "45257189",
  "password": "Dolopiola123",
  "role": "USER"
}
### POST2
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
"name": "Pachi",
"surname": "Sepulveda",
"identityNumber": "44462927",
"password": "12345678",
"role": "USER"
}

###DELETE
DELETE http://localhost:8080/api/users/2

###LOGIN
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "identityNumber": "45257189",
  "password": "Dolopiola123"
}

###LOGIN2
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "identityNumber": "44462927",
  "password": "12345678"
}


### PLATES

### POST
POST http://localhost:8080/api/plates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1OTk1NjE5OSwiZXhwIjoxNzU5OTYzMzk5fQ.QvanHZ6RQDXhXLcFG9NWgyUmsOooRr1YtMyPYke25uw

{
    "number": "RAU 123",
    "userId": 1
}

### GET
GET http://localhost:8080/api/plates/user/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1NTk4ODgyMSwiZXhwIjoxNzU1OTg5NzIxfQ.k5DAE1S7MhDAT0xd6T4ZWx3JKxLltxxG_9-vxISPMII

### POST 2
POST http://localhost:8080/api/plates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1OTUyNTQ3MiwiZXhwIjoxNzU5NTMyNjcyfQ.9eY8qh9PFuE5nZlLrhCmrjvDTyPLNwZT02kC4f2wOl4

{
    "number": "RAU 123"
}

### GET
GET http://localhost:8080/api/plates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1NzIwMDM1OSwiZXhwIjoxNzU3MjAxMjU5fQ.rb7cGoeeuX1gs1aRJoWPIaNVL0e-ymBVXdfTfFyvfMM


### PARKINGS

### GETALL
GET http://localhost:8080/api/parkings
Accept: application/json

### GETBYID
GET http://localhost:8080/api/parkings/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1NzIwMDM1OSwiZXhwIjoxNzU3MjAxMjU5fQ.rb7cGoeeuX1gs1aRJoWPIaNVL0e-ymBVXdfTfFyvfMM

### POST
POST http://localhost:8080/api/parkings/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc2MDMwMTU0MywiZXhwIjoxNzYwMzA4NzQzfQ.gh78Xbyy1bEI2XdoRy7dsLwVbd9I0Jx7NUEbs5lvZ7E

{
  "plateId": 6,
  "address": "Av.Mitre 10",
  "durationMinutes": 220,
  "status": "ACTIVE",
  "price": 100
}

### GET Por Finalizar
GET http://localhost:8080/api/parkings/about-to-finish/map
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1MzM2ODY3NywiZXhwIjoxNzUzMzY5NTc3fQ.75Wk4EwrbEKGzhsnGftJgZhvdpnapA3Lwa0BDFksewk

### DELETE
DELETE http://localhost:8080/api/parkings/1

### FINISH
POST http://localhost:8080/api/parkings/finish/17
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1MzkxMTk0MywiZXhwIjoxNzUzOTEyODQzfQ.ojm6bniTIbCSm5NWUUAkkzpEfI3vMuZej-OIz6LiFZM

### History
GET http://localhost:8080/api/parkings/history/user?limit=3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1NzE4OTExOSwiZXhwIjoxNzU3MTkwMDE5fQ.nyfcEiXQGiGHkOy6MrlTjJoXZq2x0EpAvbmWQp1GAKM

### History Get all
GET http://localhost:8080/api/parkings/history/user/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1ODI0MDU3MywiZXhwIjoxNzU4MjQxNDczfQ.nqqT7P3xaYzCp05emAztHQ84hNuAg6FMeOWmvLPu6hY

### History Get 3
GET http://localhost:8080/api/parkings/history/last-three
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1ODI0MDU3MywiZXhwIjoxNzU4MjQxNDczfQ.nqqT7P3xaYzCp05emAztHQ84hNuAg6FMeOWmvLPu6hY


### FINES

###GET
GET http://localhost:8080/api/fines
Accept: application/json

###GETBYID
GET http://localhost:8080/api/fines/1
Accept: application/json

###POST
POST http://localhost:8080/api/fines
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc2MDI4MjIzOCwiZXhwIjoxNzYwMjg5NDM4fQ.0hvaX4WXQI3y-5kE5dfJEo4aoL5GjE3ah3llVdlr9Oo

{
  "description": "Multa",
  "amount": 100000,
  "datetime": "2024-05-18T11:30:00",
  "address": "Av.Mitre 100",
  "plate": {
    "id": 28
  }
}

### GETBYUSERID
GET http://localhost:8080/api/fines/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc2MDIyMTk0NSwiZXhwIjoxNzYwMjI5MTQ1fQ.T7Z4tGzgD35RxTZMFy_U0sgB6GcESYnOEAE_Rtojk8Q


###DELETE
DELETE http://localhost:8080/api/fines/1


###BALANCE TRANSACTION

### ADD
POST http://localhost:8080/api/balance/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc2MTA1NTQ4OSwiZXhwIjoxNzYxMDYyNjg5fQ.SZ2A2HmYktOeNOEIuSaPqni7NQ9T3ryfaGtMQAThFcA

{
  "amount": 1000
}