##USERS

###GETALL
GET http://localhost:8080/api/users
Accept: application/json

###GETBYID
GET http://localhost:8080/api/users/id/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1MjAwNjQ2MCwiZXhwIjoxNzUyMDA3MzYwfQ.0cq8HSoK6cbahQNdVfvy1HJCWJ_ptI3EZykwx-X9ukM


###POST
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "dolly",
  "surname": "HERRERA GARCIA DA ROSA",
  "identityNumber": "45257189",
  "password": "dolopiola123",
  "role": "USER"
}
### POST2
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
"name": "Pachi",
"surname": "Sepulveda",
"identityNumber": "44462927",
"password": "12345678",
"role": "USER"
}

###DELETE
DELETE http://localhost:8080/api/users/2

###LOGIN
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "identityNumber": "45257189",
  "password": "dolopiola123"
}

###LOGIN2
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "identityNumber": "44462927",
  "password": "12345678"
}


### PLATES

### POST
POST http://localhost:8080/api/plates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1MjAwNjQ2MCwiZXhwIjoxNzUyMDA3MzYwfQ.0cq8HSoK6cbahQNdVfvy1HJCWJ_ptI3EZykwx-X9ukM

{
    "number": "AH 192 WL",
    "userId": 1
}

### GET
GET http://localhost:8080/api/plates/user/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1NTk4ODgyMSwiZXhwIjoxNzU1OTg5NzIxfQ.k5DAE1S7MhDAT0xd6T4ZWx3JKxLltxxG_9-vxISPMII

### POST 2
POST http://localhost:8080/api/plates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1NTk5Mzc3MSwiZXhwIjoxNzU1OTk0NjcxfQ.zy0m91tJe3A9B4C7tnxl5qC5ljSYqWYCqXET6Nm4enE

{
    "number": "ABC 124"
}

### GET
GET http://localhost:8080/api/plates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NTI1NzE4OSIsImlhdCI6MTc0OTQwMjcxOSwiZXhwIjoxNzQ5NDAzNjE5fQ.FSYckSmBSB1qlbvr0p06KWzKUpjaU_z5LXrqs-F-_lY


### PARKINGS

### GETALL
GET http://localhost:8080/api/parkings
Accept: application/json

### GETBYID
GET http://localhost:8080/api/parkings/1
Accept: application/json

### POST
POST http://localhost:8080/api/parkings/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1MzkxMTk0MywiZXhwIjoxNzUzOTEyODQzfQ.ojm6bniTIbCSm5NWUUAkkzpEfI3vMuZej-OIz6LiFZM

{
  "userId": 2,
  "plateId": 2,
  "address": "Av.Mitre 10",
  "durationMinutes": 10,
  "status": "ACTIVE",
  "price": 0
}

### GET Por Finalizar
GET http://localhost:8080/api/parkings/about-to-finish/map
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1MzM2ODY3NywiZXhwIjoxNzUzMzY5NTc3fQ.75Wk4EwrbEKGzhsnGftJgZhvdpnapA3Lwa0BDFksewk

### DELETE
DELETE http://localhost:8080/api/parkings/1

### FINISH
POST http://localhost:8080/api/parkings/finish/17
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1MzkxMTk0MywiZXhwIjoxNzUzOTEyODQzfQ.ojm6bniTIbCSm5NWUUAkkzpEfI3vMuZej-OIz6LiFZM

### History
GET http://localhost:8080/api/parkings/history/user/2?limit=3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1MzkxMDk5MywiZXhwIjoxNzUzOTExODkzfQ.Wm6e_UEcjePWqg6O8g9Ucva0MiylhmG85GT8DiM33sw


### FINES

###GET
GET http://localhost:8080/api/fines
Accept: application/json

###GETBYID
GET http://localhost:8080/api/fines/1
Accept: application/json

###POST
POST http://localhost:8080/api/fines
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1NTkwOTIyNSwiZXhwIjoxNzU1OTEwMTI1fQ.zHUwDr3PzdNKBJ4BQaFYX-n1m7HDx884wIiS1yMuz8Q

{
  "description": "Adulterar tarjetas de estacionamiento",
  "amount": 15000,
  "datetime": "2024-05-18T11:30:00",
  "plate": {
    "id": 2
  }
}

### GETBYUSERID
GET http://localhost:8080/api/fines/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDQ2MjkyNyIsImlhdCI6MTc1NTk5Mzc3MSwiZXhwIjoxNzU1OTk0NjcxfQ.zy0m91tJe3A9B4C7tnxl5qC5ljSYqWYCqXET6Nm4enE


###DELETE
DELETE http://localhost:8080/api/fines/1