##USERS

###GETALL
GET http://localhost:8080/api/users
Accept: application/json

###GETBYID
GET http://localhost:8080/api/users/2
Accept: application/json

###POST
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "dolly",
  "surname": "HERRERA GARCIA DA ROSA",
  "identityNumber": "45257189",
  "password": "dolopiola123",
  "role": "USER"
}
### POST2
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
"name": "Pachi",
"surname": "Sepulveda",
"identityNumber": "44462927",
"password": "12345678",
"role": "USER"
}

###DELETE
DELETE http://localhost:8080/api/users/2

###LOGIN
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "identityNumber": "45257189",
  "password": "dolopiola123"
}


### PLATES

### POST
POST http://localhost:8080/api/plates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NTI1NzE4OSIsImlhdCI6MTc0ODgyNzQ3NywiZXhwIjoxNzQ4ODI4Mzc3fQ.GV73-V2Dv2V9_m3mbF38TOx7BnpNcUeun7IGcGK3mIY

{
    "number": "AH 192 WL",
    "parked": false,
    "user": {
      "id": 14
    }
}


### PARKINGS

### GETALL
GET http://localhost:8080/api/parkings
Accept: application/json

### GETBYID
GET http://localhost:8080/api/parkings/1
Accept: application/json

### POST
POST http://localhost:8080/api/parkings/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NTI1NzE4OSIsImlhdCI6MTc0ODg3NDkwMCwiZXhwIjoxNzQ4ODc1ODAwfQ.OglXBe8jSazVpSqV5ilqRyHSAgi4n4GoRYX6fCNyPA4

{
  "user": {
    "id": 14
  },
  "plate": {
    "id": 4
  },
  "address": "Tupu 123",
  "durationMinutes": 10,
  "status": "ACTIVE",
  "price": 0
}

### GET Por Finalizar
GET http://localhost:8080/api/parkings/about-to-finish/map
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NTI1NzE4OSIsImlhdCI6MTc0ODgyNzQ3NywiZXhwIjoxNzQ4ODI4Mzc3fQ.GV73-V2Dv2V9_m3mbF38TOx7BnpNcUeun7IGcGK3mIY

### DELETE
DELETE http://localhost:8080/api/parkings/1


### FINES

###GET
GET http://localhost:8080/api/fines
Accept: application/json

###GETBYID
GET http://localhost:8080/api/fines/1
Accept: application/json

###POST
POST http://localhost:8080/api/fines
Content-Type: application/json

{
  "description": "Estacionado en una ochava",
  "amount": 100000,
  "datetime": "2025-05-18T19:57:00",
  "plate": {
    "id": 1
  }
}

###DELETE
DELETE http://localhost:8080/api/fines/1