services:
  backend-parking:
    container_name: backend-parking
    image: backend:v1.0.0
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      - mired
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

networks:
  mired:
    external: true